# ~/.config/starship.toml

## FIRST LINE/ROW: Info & Status
[directory]
truncation_length = 3
truncate_to_repo = true
truncation_symbol = " "

# Last param in the first line/row
[cmd_duration]
min_time = 500
format = "[ $duration]($style)"


## SECOND LINE/ROW: Prompt
[shell]
fish_indicator = ""
powershell_indicator = "_"
bash_indicator = '\(bash\)'
zsh_indicator = '\(zsh\)'
unknown_indicator = '\(mystery shell\)'
disabled = false

[git_status]
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = "*${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[battery]
full_symbol = "🔋 "
charging_symbol = "⚡️ "
discharging_symbol = "💀 "

[[battery.display]]
threshold = 15
style = "bold red"
